name: Build and Deploy ASP.NET Core App

on:
  push:
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: dotnet restore ./app

    - name: Build
      run: dotnet build ./app --configuration Release --no-restore

    - name: Test
      run: dotnet test ./app --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish ./app -c Release -o published

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapp6rqvjrpyhsxqe'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: published
